const machine = [
  {
    id: 1,
    productName: "Atlantis classic 2 option",
    price: "12000 /-",
    mrp: "16500 /-",
    title: "Coffee | Hot Coffee | Tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation.",
    machineFeature: [
      "Quick service",
      "Experienced serivice engineer",
      "Home service",
      "24*7 Active",
      "COD",
      "Free shiping",
    ],
    images: [
      "/home/classic.png",
      "/classic2/classic2.jpeg",
      "/classic2/classic1.jpeg",
      "/classic2/classic3.jpeg",
      "/classic2/classic4.jpeg",
    ],
  },
  {
    id: 6,
    productName: "Atlantis neo 3 options",
    price: "16500 /-",
    mrp: "23250 /-",
    title: "Coffee | Tea | Soup | Fresh Hot Water",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/home/neo.png",
      "/neo3/neo1.jpeg",
      "/neo3/neo2.jpeg",
      "/neo3/neo3.jpeg",
      "/neo3/neo4.jpeg",
      "/neo3/neo5.jpeg",
    ],
  },
  {
    id: 10,
    productName: "Atlantis select",
    price: "22000/-",
    mrp: "31500 /-",
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/select/select.jpg",
      "/select/select1.jpg",
      "/select/select2.jpg",
      "/select/select3.jpg",
    ],
  },
  {
    id: 2,
    productName: "Atlantis classic 3 option",
    price: "15700 /-",
    mrp: "22000 /-",
    title: "coffee | hot coffe | tea and soup",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/home/classic.png",
      "/classic3/classic1.jpeg",
      "/classic3/classic2.jpeg",
      "/classic3/classic3.jpeg",
    ],
  },
  {
    id: 3,
    productName: "Atlantis classic 4 option",
    price: "16950 /-",
    mrp: "23950/-",
    title: "coffee | hot coffe | tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/home/classic.png",
      "/classic4/classic1.jpeg",
      "/classic4/classic2.jpeg",
      "/classic4/classic3.jpeg",
      "/classic4/classic4.jpeg",
    ],
  },
  {
    id: 4,
    productName: "Atlantis neo 2 option",
    price: "13500 /-",
    mrp: "18750/-",
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/home/neo.png",
      "/neo2/neo1.jpeg",
      "/neo2/neo2.jpeg",
      "/neo2/neo3.jpeg",
      "/neo2/neo4.jpeg",
      "/neo2/neo5.jpeg",
    ],
  },

  {
    id: 8,
    productName: "Atlantis neo 4",
    price: 785,
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/home/neo.png",
      "/neo4/neo1.jpeg",
      "/neo4/neo2.jpeg",
      "/neo4/neo3.jpg",
    ],
  },

  {
    id: 9,
    productName: "Atlantis brow",
    price: 785,
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: ["/brow/brow1.webp", "/brow/brow2.webp"],
  },

  {
    id: 11,
    productName: "Atlantis cool",
    price: 785,
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/cool/cool.jpg",
      "/cool/cool1.jpg",
      "/cool/cool2.jpg",
      "/cool/cool3.jpg",
    ],
  },
];

const product = [
  {
    id: 1,
    productName: "Cappuccino coffee premix 3 in 1",
    price: "400 /-",
    mrp: "515 /-",
    title: "Milk | Coffee | Suger",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/cappuccino/cappuccino1.jpg",
      "/product/cappuccino/cappuccino2.jpg",
      "/product/cappuccino/cappuccino3.jpg",
      "/product/cappuccino/cappuccino4.jpg",
      "/product/cappuccino/cappuccino5.jpg",
    ],
  },
  {
    id: 2,
    productName: "Express tea premix",
    price: "300 /-",
    mrp: "430/-",
    title: "Tea ",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/cexpress/cexpress1.jpg",
      "/product/cexpress/cexpress2.jpg",
      "/product/cexpress/cexpress3.jpg",
      "/product/cexpress/cexpress4.jpg",
    ],
  },
  {
    id: 3,
    productName: "Kadak chai",
    price: "300 /-",
    mrp: "395 /-",
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/chai/chai1.jpg",
      "/product/chai/chai2.jpg",
      "/product/chai/chai3.jpg",
      "/product/chai/chai4.jpg",
    ],
  },
  {
    id: 4,
    productName: "Coffe premix",
    price: "400/-",
    mrp: "515/-",
    title: "Coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/coffee/coffee1.jpg",
      "/product/coffee/coffee2.jpg",
      "/product/coffee/coffee3.jpg",
      "/product/coffee/coffee4.jpg",
      "/product/coffee/coffee5.jpg",
    ],
  },
  {
    id: 6,
    productName: "Tea Premix instant",
    price: "370/-",
    mrp: "415/-",
    title: "tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/coffeepri/teapri1.jpg",
      "/product/coffeepri/teapri2.jpg",
      "/product/coffeepri/teapri3.jpg",
      "/product/coffeepri/teapri4.jpg",
      "/product/coffeepri/teapri5.jpg",
      "/product/coffeepri/teapri6.jpg",
    ],
  },
  {
    id: 7,
    productName: "Masala tea premix",
    price: "320/-",
    mrp: "430 /-",
    title: "tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/express/express1.jpg",
      "/product/express/express2.jpg",
      "/product/express/express3.jpg",
      "/product/express/express4.jpg",
    ],
  },
  {
    id: 8,
    productName: "Lemon grass ginger express",
    price: "300/-",
    mrp: "430/-",
    title: "lemon | grass | ginger",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/ginexpress/ginexpress1.jpg",
      "/product/ginexpress/ginexpress2.jpg",
      "/product/ginexpress/ginexpress3.jpg",
      "/product/ginexpress/ginexpress4.jpg",
    ],
  },
  {
    id: 9,
    productName: "Ginger premix",
    price: "380/-",
    mrp: "495/-",
    title: "Ginger",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/ginger/ginger1.jpg",
      "/product/ginger/ginger2.jpg",
      "/product/ginger/ginger3.jpg",
      "/product/ginger/ginger4.jpg",
      "/product/ginger/ginger5.jpg",
    ],
  },
  {
    id: 10,
    productName: "Gold coffee premix",
    price: "450/-",
    mrp: "675/-",
    title: "coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/gold/gold1.jpg",
      "/product/gold/gold2.jpg",
      "/product/gold/gold3.jpg",
      "/product/gold/gold4.jpg",
      "/product/gold/gold5.jpg",
    ],
  },
  {
    id: 11,
    productName: "Kadak coffee",
    price: "300/-",
    mrp: "395/-",
    title: "coffee | hot coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/kcoffee/kcoffee1.jpg",
      "/product/kcoffee/kcoffee2.jpg",
      "/product/kcoffee/kcoffee3.jpg",
      "/product/kcoffee/kcoffee4.jpg",
      "/product/kcoffee/kcoffee5.jpg",
    ],
  },
  {
    id: 12,
    productName: "Lemon grass ginger flavour",
    price: "380/-",
    mrp: "495/-",
    title: "Lemon | tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/lemongrass/lemongrass1.jpg",
      "/product/lemongrass/lemongrass2.jpg",
      "/product/lemongrass/lemongrass3.jpg",
      "/product/lemongrass/lemongrass4.jpg",
      "/product/lemongrass/lemongrass5.jpg",
    ],
  },
  {
    id: 13,
    productName: "Lemon tea with masala",
    price: "280/-",
    mrp: "335/-",
    title: "coffee | hot coffee |tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/lemontea/lemontea1.jpg",
      "/product/lemontea/lemontea2.jpg",
      "/product/lemontea/lemontea3.jpg",
      "/product/lemontea/lemontea4.jpg",
      "/product/lemontea/lemontea5.jpg",
      "/product/lemontea/lemontea6.jpg",
    ],
  },
  {
    id: 14,
    productName: "Coffee ice",
    price: "400/-",
    mrp: "500/-",
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: ["/product/nice/nice1.jpg", "/product/nice/nice2.jpg"],
  },
  {
    id: 15,
    productName: "Nukkad coffee",
    price: "280/-",
    mrp: "360/-",
    title: "coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/nukkad/nukkad1.jpg",
      "/product/nukkad/nukkad2.jpg",
      "/product/nukkad/nukkad3.jpg",
      "/product/nukkad/nukkad4.jpg",
      "/product/nukkad/nukkad5.jpg",
    ],
  },
  {
    id: 16,
    productName: "Coffee powder",
    price: "400/-",
    mrp: "480/-",
    title: "coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/pcoffee/pcoffee1.jpg",
      "/product/pcoffee/pcoffee2.jpg",
      "/product/pcoffee/pcoffee3.jpg",
      "/product/pcoffee/pcoffee4.jpg",
    ],
  },
  {
    id: 17,
    productName: "Instant coffee premix",
    price: "300/-",
    mrp: "430/-",
    title: "coffee | hot coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/preexpress/preexpress1.jpg",
      "/product/preexpress/preexpress2.jpg",
      "/product/preexpress/preexpress3.jpg",
      "/product/preexpress/preexpress4.jpg",
    ],
  },
  {
    id: 18,
    productName: "Rich whitener",
    price: "300/-",
    mrp: "345/-",
    title: "Milk",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/rich/rich1.jpg",
      "/product/rich/rich2.jpg",
      "/product/rich/rich3.jpg",
      "/product/rich/rich4.jpg",
      "/product/rich/rich5.jpg",
    ],
  },
  {
    id: 19,
    productName: "Signature coffee",
    price: "780/-",
    mrp: "885/-",
    title: "coffee | hot coffee",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/singnature/singnature1.jpg",
      "/product/singnature/singnature2.jpg",
      "/product/singnature/singnature3.jpg",
      "/product/singnature/singnature4.jpg",
    ],
  },
  {
    id: 20,
    productName: "Tomato soup powder 500g",
    price: "300/-",
    mrp: "360/-",
    title: "soup",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/soup/soup1.jpg",
      "/product/soup/soup2.jpg",
      "/product/soup/soup3.jpg",
      "/product/soup/soup4.jpg",
      "/product/soup/soup5.jpg",
    ],
  },
  {
    id: 21,
    productName: "Plus tea premix",
    price: "400/-",
    mrp: "515/-",
    title: "tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/tea/tea1.jpg",
      "/product/tea/tea2.jpg",
      "/product/tea/tea3.jpg",
      "/product/tea/tea4.jpg",
      "/product/tea/tea5.jpg",
    ],
  },
  {
    id: 22,
    productName: "Plus Tea premix masala",
    price: "400/-",
    mrp: "495/-",
    title: "tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/teamasala/teamasala1.jpg",
      "/product/teamasala/teamasala2.jpg",
      "/product/teamasala/teamasala3.jpg",
      "/product/teamasala/teamasala4.jpg",
      "/product/teamasala/teamasala5.jpg",
    ],
  },
  {
    id: 23,
    productName: "Plus Tea premix regular",
    price: "380/-",
    mrp: "450/-",
    title: "coffee,hot coffe,tea",
    descripiton:
      "At A One Vending Solutions, we provide high-quality vending machine components and reliable service solutions across Delhi NCR. Our 2-liter capacity hot tank is designed to deliver efficient and consistent hot water supply for coffee and tea vending machines, ensuring smooth and uninterrupted beverage preparation..",
    machineFeature: [
      "quick service",
      "Experienced serivice engineer",
      "home service",
      "24*7 active",
    ],
    images: [
      "/product/tearmx/tearmx1.jpg",
      "/product/tearmx/tearmx2.jpg",
      "/product/tearmx/tearmx3.jpg",
      "/product/tearmx/tearmx4.jpg",
    ],
  },
];
export { machine, product };
